# Generated by Django 3.2.24 on 2024-10-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fno', models.DecimalField(decimal_places=10, max_digits=10)),
                ('lno', models.DecimalField(decimal_places=10, max_digits=10)),
                ('result', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
