# Generated by Django 3.2.24 on 2024-10-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fun',
            name='result',
        ),
        migrations.AddField(
            model_name='fun',
            name='operands',
            field=models.CharField(default='Select the operand', max_length=20),
        ),
    ]
