# Generated by Django 3.2.24 on 2024-10-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20241004_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fun',
            name='fno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fun',
            name='lno',
            field=models.IntegerField(),
        ),
    ]
