# Generated by Django 3.2.24 on 2024-10-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20241004_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fun',
            name='fno',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fun',
            name='lno',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
