# Generated by Django 3.2.24 on 2024-10-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20241004_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('no_yor', models.PositiveIntegerField()),
                ('rate', models.PositiveIntegerField()),
                ('add_cont', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
